/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellApprovalsRouteImport } from './routes/_shell.approvals'
import { Route as ShellAuditRouteImport } from './routes/_shell.audit'
import { Route as ShellDirectoryRouteImport } from './routes/_shell.directory'
import { Route as ShellDistributionRouteImport } from './routes/_shell.distribution'
import { Route as ShellRecipientsRouteImport } from './routes/_shell.recipients'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellUploadRouteImport } from './routes/_shell.upload'
import { Route as ShellCircularsIndexRouteImport } from './routes/_shell.circulars.index'
import { Route as ShellCircularsIdRouteImport } from './routes/_shell.circulars.$id'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellApprovalsRoute = ShellApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAuditRoute = ShellAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDirectoryRoute = ShellDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDistributionRoute = ShellDistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRecipientsRoute = ShellRecipientsRouteImport.update({
  id: '/recipients',
  path: '/recipients',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUploadRoute = ShellUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCircularsIndexRoute = ShellCircularsIndexRouteImport.update({
  id: '/circulars/',
  path: '/circulars/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCircularsIdRoute = ShellCircularsIdRouteImport.update({
  id: '/circulars/$id',
  path: '/circulars/$id',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/approvals': typeof ShellApprovalsRoute
  '/audit': typeof ShellAuditRoute
  '/directory': typeof ShellDirectoryRoute
  '/distribution': typeof ShellDistributionRoute
  '/recipients': typeof ShellRecipientsRoute
  '/settings': typeof ShellSettingsRoute
  '/upload': typeof ShellUploadRoute
  '/circulars/$id': typeof ShellCircularsIdRoute
  '/circulars/': typeof ShellCircularsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/approvals': typeof ShellApprovalsRoute
  '/audit': typeof ShellAuditRoute
  '/directory': typeof ShellDirectoryRoute
  '/distribution': typeof ShellDistributionRoute
  '/recipients': typeof ShellRecipientsRoute
  '/settings': typeof ShellSettingsRoute
  '/upload': typeof ShellUploadRoute
  '/': typeof ShellIndexRoute
  '/circulars/$id': typeof ShellCircularsIdRoute
  '/circulars': typeof ShellCircularsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/approvals': typeof ShellApprovalsRoute
  '/_shell/audit': typeof ShellAuditRoute
  '/_shell/directory': typeof ShellDirectoryRoute
  '/_shell/distribution': typeof ShellDistributionRoute
  '/_shell/recipients': typeof ShellRecipientsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/upload': typeof ShellUploadRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/circulars/$id': typeof ShellCircularsIdRoute
  '/_shell/circulars/': typeof ShellCircularsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/approvals'
    | '/audit'
    | '/directory'
    | '/distribution'
    | '/recipients'
    | '/settings'
    | '/upload'
    | '/circulars/$id'
    | '/circulars/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/approvals'
    | '/audit'
    | '/directory'
    | '/distribution'
    | '/recipients'
    | '/settings'
    | '/upload'
    | '/'
    | '/circulars/$id'
    | '/circulars'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/approvals'
    | '/_shell/audit'
    | '/_shell/directory'
    | '/_shell/distribution'
    | '/_shell/recipients'
    | '/_shell/settings'
    | '/_shell/upload'
    | '/_shell/'
    | '/_shell/circulars/$id'
    | '/_shell/circulars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/approvals': {
      id: '/_shell/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ShellApprovalsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/audit': {
      id: '/_shell/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof ShellAuditRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/directory': {
      id: '/_shell/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof ShellDirectoryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/distribution': {
      id: '/_shell/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof ShellDistributionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/recipients': {
      id: '/_shell/recipients'
      path: '/recipients'
      fullPath: '/recipients'
      preLoaderRoute: typeof ShellRecipientsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/upload': {
      id: '/_shell/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof ShellUploadRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/circulars/': {
      id: '/_shell/circulars/'
      path: '/circulars'
      fullPath: '/circulars/'
      preLoaderRoute: typeof ShellCircularsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/circulars/$id': {
      id: '/_shell/circulars/$id'
      path: '/circulars/$id'
      fullPath: '/circulars/$id'
      preLoaderRoute: typeof ShellCircularsIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellApprovalsRoute: typeof ShellApprovalsRoute
  ShellAuditRoute: typeof ShellAuditRoute
  ShellDirectoryRoute: typeof ShellDirectoryRoute
  ShellDistributionRoute: typeof ShellDistributionRoute
  ShellRecipientsRoute: typeof ShellRecipientsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellUploadRoute: typeof ShellUploadRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellCircularsIdRoute: typeof ShellCircularsIdRoute
  ShellCircularsIndexRoute: typeof ShellCircularsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellApprovalsRoute: ShellApprovalsRoute,
  ShellAuditRoute: ShellAuditRoute,
  ShellDirectoryRoute: ShellDirectoryRoute,
  ShellDistributionRoute: ShellDistributionRoute,
  ShellRecipientsRoute: ShellRecipientsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellUploadRoute: ShellUploadRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellCircularsIdRoute: ShellCircularsIdRoute,
  ShellCircularsIndexRoute: ShellCircularsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
